# Generated by Django 4.1.3 on 2023-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                ("image1", models.ImageField(upload_to="cars/", verbose_name="image1")),
                (
                    "image2",
                    models.ImageField(
                        blank=True, upload_to="cars/", verbose_name="image2"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, upload_to="cars/", verbose_name="image3"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, upload_to="cars/", verbose_name="image4"
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True, upload_to="cars/", verbose_name="image5"
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True, upload_to="cars/", verbose_name="image6"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "car",
                "verbose_name_plural": "cars",
                "ordering": ("title",),
            },
        ),
    ]
