# Generated by Django 4.1.3 on 2023-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="color"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="condition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="condition"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="cylinders",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="cylinders"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="doors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="doors"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="drive_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="drive_type"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_size",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="engine_size"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="fuel_type"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="mileage"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="model"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="transmission"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="vin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="vin"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="year"
            ),
        ),
    ]
