# Generated by Django 4.1.3 on 2023-04-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_car_color_car_condition_car_cylinders_car_doors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("phone", models.CharField(max_length=255, verbose_name="phone")),
                ("email", models.CharField(max_length=255, verbose_name="email")),
                ("comment", models.CharField(max_length=255, verbose_name="comment")),
            ],
        ),
    ]
