# Generated by Django 3.2.5 on 2023-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('compact', 'Compact'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('convertible', 'Convertible'), ('coupe', 'Coupe')], default='Compact', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
