# Generated by Django 3.2.5 on 2023-04-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230424_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCarInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, null=True, verbose_name='color')),
                ('number_owners', models.CharField(max_length=20)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
